services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: test_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - test-network
    restart: unless-stopped

  backend:
    container_name: app-api
    image: dockerize-spring-boot-app:1.0.0
    ports:
      - 8088:8088
    networks:
      - test-network
    depends_on:
      - postgres

networks:
  test-network:
    driver: bridge

volumes:
  postgres:
    driver: local